# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-04 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_plan_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
