# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-03 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200503_0924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PremiumPlan',
        ),
    ]
