# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-03 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_fulldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulldocument',
            name='document_text',
            field=models.TextField(default=''),
        ),
    ]
