# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-03 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20200503_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulldocument',
            name='premium',
            field=models.BooleanField(default=True),
        ),
    ]
